services:
  thredds:
    image: thredds:latest
    #image: europe-west1-docker.pkg.dev/niva-cd/images/thredds:latest
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    environment:
      - BASE_URL=http://localhost
      - XVIEW_URL=http://localhost:8000/xview/panel
    volumes:
      - ./catalog/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./catalog/datasets:/datasets
      - ./catalog/ncml-to-iso.xsl:/usr/local/tomcat/webapps/thredds/WEB-INF/classes/resources/xsl/nciso/UnidataDD2MI.xsl

  pycsw:
    image: geopython/pycsw:latest
    environment:
      - PYCSW_SERVER_URL=http://localhost:8100
    ports:
      - 8100:8100
    volumes:
      - ./catalog/metadata/pycsw.yml:/etc/pycsw/pycsw.yml
      - ./catalog/metadata/:/home/pycsw/data/
  populate-metadata:
    image: geopython/pycsw:latest
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pycsw-admin.py  delete-records -c /etc/pycsw/pycsw.yml -y
        pycsw-admin.py  load-records -p data -c /etc/pycsw/pycsw.yml
    environment:
      - PYCSW_SERVER_URL=http://pycsw:8000
    volumes:
      - ./catalog/metadata/pycsw.yml:/etc/pycsw/pycsw.yml
      - ./catalog/metadata/:/home/pycsw/data/
    depends_on:
      pycsw:
        condition: service_started