version: '3.5'
services:
  thredds:
    image: europe-west1-docker.pkg.dev/niva-cd/images/thredds:latest
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - ./catalog/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./catalog:/datasets
      - ./catalog/UnidataDD2MI.xsl:/usr/local/tomcat/webapps/thredds/WEB-INF/classes/resources/xsl/nciso/UnidataDD2MI.xsl